modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/gizmo-ds/chatjs-mod/issues"
license = "LGPL-3.0"

[[mods]]
modId = "chatjs"
version = "${version}"
displayName = "ChatJS"
authors = "Gizmo"
description = '''
ChatJS
'''
logoFile = "chatjs_logo.png"
displayURL = "https://github.com/gizmo-ds/chatjs-mod"

[[dependencies.chatjs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatjs]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.chatjs]]
modId = "cloth_config"
mandatory = false
versionRange = "[11.,)"
ordering = "NONE"
side = "CLIENT"
