# suppress inspection "SpellCheckingInspection" for whole file
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=false
org.gradle.configuration-cache=false
# Mod properties
mod.id=chatjs
mod.name=ChatJS
mod.group=dev.aika.chatjs
mod.version=0.1.0
mod.release_type=release
mod.game_version_supports=1.20.1
mod.enabled_platforms=fabric,forge
# Minecraft properties
minecraft_version=1.20.1
parchment_version=2023.09.03
# Publishing
modrinth_id=eYYNtb4M
curseforge_id=1317770
