[plugins]
dotenv = { id = "co.uzzu.dotenv.gradle", version = "4.0.0" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version = "2.1.6" }
moddev = { id = "net.neoforged.moddev", version = "2.0.107" }

[versions]
lombok = "1.18.38"
minecraft = "1.21.1"
parchment = "2024.11.17"
neoforge = "21.1.206"
kubejs = "2101.7.2-build.261"
clothconfig = "15.0.130"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
kubejs = { module = "dev.latvian.mods:kubejs-neoforge", version.ref = "kubejs" }
clothconfig = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "clothconfig" }
norealmsbutton = { version = "ZPsxuqtp", module = "maven.modrinth:no-realms-button" } # 2.0.2
