# OpenAI/Grok/DeepSeek/DouBao/Gemini/Kimi/Qwen/Custom
provider = "OpenAI"

[custom_provider]
model = "qwen-turbo"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
# Optional
models_path = "/models"
# Optional
chat_completion_path = "/chat/completions"

[http_client]
rps = 0.5 # Requests per second
request_timeout = 10 # Seconds
